services:
  broker:
    image: apache/kafka:4.1.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    networks:
      - recommendation_system
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  recommendation_service:
    image: snds_prfct/recommendation-service:0.1
    build: recommendation-service/
    container_name: recommendation_service
    depends_on:
      - broker
    ports:
      - "8080:8080"
    networks:
      - recommendation_system
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:29092

  main_service:
    image: snds_prfct/main-service:0.1
    build: main-service/
    container_name: main_service
    depends_on:
      - broker
    ports:
      - "8081:8080"
    networks:
      - recommendation_system
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:29092

networks:
  recommendation_system:
    driver: bridge
